name: build-test

on:
  push:
    branches: [ test-actions ]
  pull_request:
    branches: [ trst-actions ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps
      run: |
        sudo apt update
        sudo apt install -y bison
        sudo apt install -y ruby
    
    - name: Main
      run: |
        sudo apt-get update
        git clone https://github.com/Hadeweka/Shidacea/tree/test-actions Shidacea --recursive
        mkdir build
        cd build
        cmake ..
        make
        
