name: build-test

on:
  push:
    branches: [ test-actions ]
  pull_request:
    branches: [ test-actions ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps
      run: |
        sudo apt update
        sudo apt install -y bison
        sudo apt install -y ruby
        sudo apt install -y libx11-dev
        sudo apt install -y libudev-dev
        sudo apt install -y libopenal-dev
        sudo apt install -y libvorbis-dev
        sudo apt install -y libflac-dev
        sudo apt install -y xorg-dev
        sudo apt install -y libglu1-mesa-dev
        echo "Dependencies installed."
        echo "g++ version is:"
        g++ --version
    
    - name: Main
      run: |
        git submodule init
        git submodule update --recursive
        mkdir build
        cd build
        cmake ..
        make
        
